import test from 'node:test';
import assert from 'node:assert/strict';
import {objectInput,mergeOptions,decodePresence,initialRun,transition,rustPlaygroundUrl} from '../src/labs.js';
test('option precedence replaces whole nested values and preserves input',()=>{const b={a:{x:1,y:2},effort:'low'},p={effort:'medium'};const r=mergeOptions(b,p,{a:{x:3},effort:'high'});assert.deepEqual(r.effective.a,{x:3});assert.equal(r.sources.a,'Run');assert.equal(r.effective.effort,'high');assert.deepEqual(b.a,{x:1,y:2});});
test('reject null and non-object option roots',()=>{for(const v of ['null','[]','2','"x"'])assert.throws(()=>objectInput(v));assert.throws(()=>objectInput('{oops'));});
test('presence distinguishes omission and null and rejects contradictions',()=>{assert.deepEqual(decodePresence({present:false,value:null}),{});assert.deepEqual(decodePresence({present:true,value:null}),{note:null});for(const x of [{present:false,value:'x'},{present:true},{present:0,value:null},{present:true,value:'x',other:1}])assert.throws(()=>decodePresence(x));});
test('idle cancel creates a new segment without replacing old outcomes',()=>{const waiting=transition(initialRun(),'wait');const cancelled=transition(waiting,'cancel');assert.equal(cancelled.segment,2);assert.deepEqual(cancelled.history,[{segment:1,status:'Waiting'},{segment:2,status:'Cancelled'}]);assert.equal(waiting.status,'Waiting');assert.equal(transition(cancelled,'resume').status,'Cancelled');});
test('resume preserves interruption and starts a new interval',()=>{let s=transition(initialRun(),'stop');s=transition(s,'resume');s=transition(s,'finish');assert.deepEqual(s.history,[{segment:1,status:'Interrupted'},{segment:2,status:'Succeeded'}]);});
test('Rust external URL preserves code without interpreting it',()=>{const code='fn main() { println!("한글 & # ?"); }';const u=new URL(rustPlaygroundUrl(code));assert.equal(u.origin,'https://play.rust-lang.org');assert.equal(u.searchParams.get('code'),code);assert.equal(u.searchParams.get('edition'),'2024');});
