import './style.css';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import GithubSlugger from 'github-slugger';
import hljs from 'highlight.js/lib/core';
import rust from 'highlight.js/lib/languages/rust';
import json from 'highlight.js/lib/languages/json';
import bash from 'highlight.js/lib/languages/bash';
import toml from 'highlight.js/lib/languages/ini';
import python from 'highlight.js/lib/languages/python';
import {objectInput,mergeOptions,decodePresence,initialRun,transition,rustExamples,rustPlaygroundUrl} from './labs.js';
for(const [n,l] of Object.entries({rust,json,bash,sh:bash,toml,python})) hljs.registerLanguage(n,l);
const $ = s => document.querySelector(s);
const escape = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = {search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',book:'<path d="M3 5h7l2 2 2-2h7v15h-7l-2 2-2-2H3zM12 7v15"/>',code:'<path d="m8 5-6 7 6 7m8-14 6 7-6 7m-2-18-4 22"/>',moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',check:'<path d="m5 12 4 4L19 6"/>'};
const icon = key=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">${icons[key]}</svg>`;
const base=(import.meta.env.VITE_CONTENT_BASE_URL||new URL('content/',document.baseURI).href).replace(/\/?$/,'/');
let catalog, chapters=[], currentPath='', token=0, labState=initialRun(), activeLab='options', searchTimer;
let stored;try{stored=JSON.parse(localStorage.getItem('wickle-book-v02')||'{}');}catch{stored={};}
stored = stored && typeof stored === 'object' ? stored : {};
const state={completed:Array.isArray(stored.completed)?stored.completed:[],last:typeof stored.last==='string'?stored.last:'',dark:!!stored.dark};
const save=()=>{try{localStorage.setItem('wickle-book-v02',JSON.stringify(state));}catch{toast('이 브라우저에서는 진도를 저장할 수 없습니다.');}};
const readHref=p=>'#/read/'+encodeURIComponent(p);
const chapterGroup=n=>n<=2?'준비 · Rust와 설계':n<=14?'01 · 엔진의 기반':n<=24?'02 · 실행과 확장':n<=36?'03 · 어댑터와 첫 완성':n<=46?'04 · 0.2.0의 새 계약':n<=49?'05 · 중단과 진단':n<=57?'06 · 공급자 연결':'07 · 0.2.0 완성';
async function getJSON(url){const response=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`자료를 불러오지 못했습니다 (${response.status}).`);return response.json();}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');setTimeout(()=>$('#toast')?.classList.remove('visible'),2600);}
function progress(){const count=chapters.filter(c=>state.completed.includes(c.path)).length;$('#progress-text').textContent=`${count} / ${chapters.length}장 완료`;$('#progress-bar').style.width=`${count/chapters.length*100}%`;}
function shell(){
 document.documentElement.dataset.theme=state.dark?'dark':'light';
 $('#app').innerHTML=`<header class="topbar"><div class="brand"><button class="mobile-menu icon-button" aria-label="목차 열기">${icon('menu')}</button><a href="#/" class="brand-link"><span class="monogram">w.</span><strong>wickle<span class="brand-divider">/</span><span class="brand-book">the book</span></strong></a><span class="version">v0.2.0</span></div><div class="top-actions"><button id="search-open" class="search-trigger">${icon('search')}<span>교재 검색</span><kbd>⌘ K</kbd></button><a href="#/playground" class="playground-link">${icon('code')}<span>Playground</span></a><button id="theme" class="icon-button" aria-label="${state.dark?'밝은':'어두운'} 테마로 변경">${icon('moon')}</button></div></header><div class="page"><div id="shade" hidden></div><aside class="sidebar" aria-label="책 목차"><div class="sidebar-top"><p class="eyebrow">THE ENGINEERING SERIES</p><a class="overview-link" href="#/">${icon('book')} 학습 안내 <span>↗</span></a></div><div id="chapter-nav"></div><div class="sidebar-bottom"><span id="progress-text"></span><div class="progress-track"><i id="progress-bar"></i></div><small>학습 진도는 이 브라우저에 저장됩니다.</small><a class="download-book" href="${base}downloads/wickle-webbook-study.zip" download>교재·코드 내려받기 ↓</a></div></aside><main id="main" tabindex="-1"></main></div><div id="toast" role="status" aria-live="polite"></div><dialog id="search-dialog" aria-label="교재 전체 검색"><div class="search-input-wrap">${icon('search')}<input id="search-input" aria-label="검색어" placeholder="개념, 챕터, 코드 파일 검색…" autocomplete="off"><button id="search-close" class="subtle">닫기 Esc</button></div><div id="search-results"></div><div class="search-hint">제목 · 강의 본문 검색 <span>↑ ↓ 이동 · Enter 열기</span></div></dialog>`;
 const groups=new Map();for(const c of chapters){const g=chapterGroup(parseInt(c.number));if(!groups.has(g))groups.set(g,[]);groups.get(g).push(c);}
 $('#chapter-nav').innerHTML=[...groups].map(([g,cs])=>`<details class="chapter-group" open><summary>${g}</summary><nav>${cs.map(c=>`<a href="${readHref(c.path)}" data-path="${escape(c.path)}"><span class="chapter-number">${c.number}</span><span>${escape(c.title.replace(/^\d+[A-Z]?장\.\s*/i,''))}</span><i class="done-mark" aria-label="완료">${state.completed.includes(c.path)?'✓':''}</i></a>`).join('')}</nav></details>`).join('')+`<details class="chapter-group"><summary>참고 자료</summary><nav>${catalog.documents.filter(d=>d.kind==='guide'&&!d.path.includes('/examples/')).map(d=>`<a href="${readHref(d.path)}">${escape(d.title)}</a>`).join('')}</nav></details>`;
 progress();
 document.querySelector('.skip').onclick=e=>{e.preventDefault();$('#main').focus();};
 $('#theme').onclick=()=>{state.dark=!state.dark;save();document.documentElement.dataset.theme=state.dark?'dark':'light';$('#theme').setAttribute('aria-label',`${state.dark?'밝은':'어두운'} 테마로 변경`);};
 $('.mobile-menu').onclick=()=>toggleMenu(true);$('#shade').onclick=()=>toggleMenu(false);
 $('#search-open').onclick=openSearch;$('#search-close').onclick=()=>$('#search-dialog').close();
 $('#search-input').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(renderSearch,100);};
 $('#search-dialog').addEventListener('click',e=>{if(e.target===$('#search-dialog'))$('#search-dialog').close();});
 document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();openSearch();}if(e.key==='Escape')toggleMenu(false);});
 $('#search-dialog').addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const links=[...$('#search-results').querySelectorAll('a')];if(!links.length)return;let i=links.indexOf(document.activeElement);i=e.key==='ArrowDown'?(i+1)%links.length:(i<=0?links.length-1:i-1);links[i].focus();}if(e.key==='Enter'&&document.activeElement===$('#search-input')){const a=$('#search-results a');if(a)a.click();}});
}
function toggleMenu(open){document.body.classList.toggle('menu-open',open);$('#shade').hidden=!open;$('.mobile-menu').setAttribute('aria-expanded',String(open));if(open)$('#chapter-nav a')?.focus();}
function openSearch(){$('#search-dialog').showModal();$('#search-input').value='';renderSearch();$('#search-input').focus();}
function renderSearch(){const q=$('#search-input').value.trim().toLocaleLowerCase();const words=q.split(/\s+/).filter(Boolean);const results=catalog.documents.filter(d=>words.every(w=>(d.title+' '+d.path+' '+d.search).toLocaleLowerCase().includes(w))).sort((a,b)=>Number(b.title.toLowerCase().includes(q))-Number(a.title.toLowerCase().includes(q))).slice(0,35);$('#search-results').innerHTML=q?results.length?results.map(d=>{const content=d.search||d.excerpt;const at=content.toLowerCase().indexOf(words[0]);return `<a href="${readHref(d.path)}"><span class="eyebrow">${d.kind==='chapter'?'CHAPTER '+d.number:d.kind.toUpperCase()}</span><strong>${escape(d.title)}</strong><small>${escape(content.slice(Math.max(0,at-35),Math.max(0,at-35)+140))}…</small></a>`;}).join(''):'<div class="empty"><strong>검색 결과가 없습니다.</strong><p>다른 개념이나 짧은 단어로 검색해 보세요.</p></div>':'<div class="empty"><p class="eyebrow">FIND YOUR NEXT IDEA</p><strong>어떤 개념을 찾고 있나요?</strong><p>PreparedStep, 소유권, 중단, schema…</p></div>';$('#search-results').querySelectorAll('a').forEach(a=>a.onclick=()=>$('#search-dialog').close());}
function home(){document.title='Wickle — Rust로 만드는 에이전트';$('#main').className='home';const count=chapters.filter(c=>state.completed.includes(c.path)).length;const resume=chapters.find(c=>c.path===state.last);$('#main').innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> A HANDS-ON ENGINEERING BOOK</p><h1>Rust를 배우며,<br>에이전트를 <em>만들다.</em></h1><p class="hero-description">소유권부터 실행 상태, 도구 호출과 장애 복구까지.<br>작은 코드에서 출발해 Wickle 0.2.0을 직접 완성하는 여정.</p><div class="hero-buttons"><a class="button primary" href="${readHref(resume?.path||'ko/00-start.md')}">${resume?'이어서 읽기':'첫 페이지 열기'} ${icon('arrow')}</a><a class="text-link" href="${readHref('ko/37-compatibility.md')}">0.1.0을 마쳤다면 <span>↗</span></a></div><div class="hero-stats"><div><strong>62</strong><span>개의 강의</span></div><div><strong>58</strong><span>단계의 구현</span></div><div><strong>13</strong><span>개의 Rust crate</span></div></div></div><div class="cover-art" aria-hidden="true"><div class="cover-top">WICKLE<br>ENGINEERING NOTES<span>VOL. 02</span></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="diagram-node node-a">input</div><div class="diagram-node node-b">agent</div><div class="diagram-node node-c">tool</div><span class="cover-symbol">w.</span><div class="cover-bottom"><span>BUILD. UNDERSTAND.<br>MAKE IT YOURS.</span><strong>0.2</strong></div></div></section><section class="learning-strip"><div><span class="eyebrow">YOUR LEARNING JOURNEY</span><h2>한 줄씩 이해하고, 한 단계씩 완성하기</h2></div><span class="journey-count">${count}<span> / 62</span></span></section><section class="paths"><a class="path-row" href="${readHref('ko/00-start.md')}"><span class="path-index">01</span><div><h3>처음부터 차근차근</h3><p>Rust 기초와 에이전트 개념부터, 실행 가능한 엔진까지.</p></div><span class="pill">00–60장</span>${icon('arrow')}</a><a class="path-row" href="${readHref('ko/37-compatibility.md')}"><span class="path-index">02</span><div><h3>0.2.0의 설계를 깊이 있게</h3><p>저장된 요청, 가역 스키마, PreparedStep과 실행 구간.</p></div><span class="pill">37–60장</span>${icon('arrow')}</a><a class="path-row" href="#/playground"><span class="path-index">03</span><div><h3>읽은 개념을 직접 실험하기</h3><p>입력과 상태를 바꾸고, 달라지는 결과를 눈으로 확인하세요.</p></div><span class="pill accent">PLAYGROUND</span>${icon('arrow')}</a></section><section class="home-bottom"><div><p class="eyebrow">LEARN THE WHY</p><h3>코드 뒤의 설계까지.</h3><p>왜 이런 경계가 필요한지, 어떤 비용을 선택했는지.<br>실패 사례와 함께 아키텍처와 패턴을 이해합니다.</p><a class="text-link" href="${readHref('ko/02b-architecture.md')}">아키텍처 강의 읽기 ↗</a></div><div class="quote-note"><span>“</span><p>패치를 적용하는 것은 복원입니다.<br>실패를 설명할 수 있을 때,<br>비로소 구현을 이해한 것입니다.</p><small>이 교재의 학습 원칙</small></div></section><footer>WICKLE / THE BOOK <span>Rust 2024 · 한국어 · v0.2.0</span></footer>`;}
async function read(path,section,myToken){const doc=catalog.documents.find(d=>d.path===path);if(!doc){notFound();return;}currentPath=path;$('#main').className='reader';$('#main').innerHTML='<p class="loading">이 장을 불러오는 중입니다…</p>';try{const content=await getJSON(base+'docs/'+doc.id+'.json');if(myToken!==token)return;document.title=doc.title+' — Wickle';const index=chapters.findIndex(d=>d.path===path);const prev=chapters[index-1],next=chapters[index+1];const complete=state.completed.includes(path);
 let html=content.markdown?DOMPurify.sanitize(marked.parse(content.body),{ADD_TAGS:['details','summary'],FORBID_TAGS:['iframe','form','input','style'],FORBID_ATTR:['style']}):`<pre><code class="language-${content.language||'text'}">${escape(content.body)}</code></pre>`;
 $('#main').innerHTML=`<div class="reader-grid"><div class="reader-column"><div class="reading-meta"><a href="#/">THE BOOK</a><span>/</span><span>${doc.kind==='chapter'?'CHAPTER '+doc.number:doc.kind.toUpperCase()}</span><a class="reading-download" href="${base+catalog.assets[path]}" download>원문 ↓</a><span class="reading-time">약 ${doc.minutes}분 읽기</span></div><article class="prose" id="article">${html}</article><div class="chapter-finish">${index>=0?`<button id="complete" class="button ${complete?'completed':'primary'}">${icon('check')} ${complete?'학습 완료됨 · 취소':'이 장 학습 완료'}</button>`:''}<a class="text-link" href="#/playground">개념 실험실 열기 ↗</a></div>${index>=0?`<nav class="pagination" aria-label="장 이동">${prev?`<a href="${readHref(prev.path)}"><small>← 이전 장</small><strong>${escape(prev.title)}</strong></a>`:'<span></span>'}${next?`<a href="${readHref(next.path)}"><small>다음 장 →</small><strong>${escape(next.title)}</strong></a>`:'<a href="#/"><small>학습 여정 마치기 →</small><strong>전체 안내로</strong></a>'}</nav>`:''}</div><aside class="page-toc" aria-label="이 장의 목차"><p class="eyebrow">ON THIS PAGE</p><nav id="section-nav"></nav><div class="toc-note">작게 구현하고,<br>실패를 관찰하고,<br>자신의 말로 설명하세요.</div></aside></div>`;
 const slugger=new GithubSlugger();const headings=[...$('#article').querySelectorAll('h1,h2,h3')];headings.forEach(h=>h.id=slugger.slug(h.textContent));$('#section-nav').innerHTML=headings.filter(h=>h.tagName==='H2').map(h=>`<a href="${readHref(path)}?section=${encodeURIComponent(h.id)}">${escape(h.textContent)}</a>`).join('');
 for(const a of $('#article').querySelectorAll('a')){const href=a.getAttribute('href')||'';if(href.startsWith('#')){a.href=readHref(path)+'?section='+encodeURIComponent(decodeURIComponent(href.slice(1)));continue;}if(/^https?:/i.test(href)){a.target='_blank';a.rel='noopener noreferrer';continue;}if(/^mailto:/i.test(href))continue;try{const u=new URL(href,'https://book.local/'+path);const dest=decodeURIComponent(u.pathname.slice(1));if(catalog.documents.some(d=>d.path===dest))a.href=readHref(dest)+(u.hash?'?section='+encodeURIComponent(decodeURIComponent(u.hash.slice(1))):'');else if(catalog.assets[dest]){a.href=base+catalog.assets[dest];a.setAttribute('download',dest.split('/').pop());a.target='_blank';a.rel='noopener';}else{const span=document.createElement('span');span.className='local-reference';span.textContent=a.textContent+' [로컬 교재]';a.replaceWith(span);}}catch{a.removeAttribute('href');}}
 for(const img of $('#article').querySelectorAll('img')){const src=img.getAttribute('src')||'';if(/^https?:/.test(src)){img.loading='lazy';continue;}const p=decodeURIComponent(new URL(src,'https://book.local/'+path).pathname.slice(1));if(catalog.assets[p])img.src=base+catalog.assets[p];else img.remove();}
 for(const pre of $('#article').querySelectorAll('pre')){const code=pre.querySelector('code');if(!code)continue;const raw=code.textContent;if(raw.length<12000){const lang=(code.className.match(/language-([^ ]+)/)||[])[1]?.split(',')[0];if(lang&&hljs.getLanguage(lang))code.innerHTML=hljs.highlight(raw,{language:lang}).value;}
 const wrap=document.createElement('div');wrap.className='code-wrap';pre.replaceWith(wrap);const bar=document.createElement('div');bar.className='code-bar';const lang=(code.className.match(/language-([^ ]+)/)||[])[1]||'code';bar.innerHTML=`<span>${escape(lang.toUpperCase())}</span><button type="button">복사</button>`;bar.querySelector('button').onclick=async()=>{try{await navigator.clipboard.writeText(raw);toast('코드를 복사했습니다.');}catch{toast('복사할 수 없습니다. 코드를 직접 선택해 주세요.');}};wrap.append(bar,pre);}
 if(index>=0){state.last=path;save();$('#complete').onclick=()=>{const at=state.completed.indexOf(path);if(at<0)state.completed.push(path);else state.completed.splice(at,1);save();progress();const done=state.completed.includes(path);$('#complete').className='button '+(done?'completed':'primary');$('#complete').innerHTML=icon('check')+(done?' 학습 완료됨 · 취소':' 이 장 학습 완료');const link=[...document.querySelectorAll('[data-path]')].find(a=>a.dataset.path===path);if(link)link.querySelector('.done-mark').textContent=done?'✓':'';};}
 if(section){document.getElementById(section)?.scrollIntoView();}else window.scrollTo(0,0);
 }catch(e){if(myToken===token)errorScreen(e.message);}}
function notFound(){$('#main').className='reader';$('#main').innerHTML='<div class="empty"><h1>찾을 수 없는 페이지입니다.</h1><p>목차에서 장을 다시 선택해 주세요.</p><a class="button primary" href="#/">학습 안내로</a></div>';}
function errorScreen(message){$('#main').innerHTML=`<div class="empty"><h1>교재를 불러오지 못했습니다.</h1><p>${escape(message)}</p><button class="button primary" id="retry">다시 시도</button></div>`;$('#retry').onclick=route;}
function playground(){document.title='Playground — Wickle';$('#main').className='playground';$('#main').innerHTML=`<div class="lab-heading"><p class="eyebrow">LEARN BY CHANGING</p><h1>작은 실험, 깊은 이해.</h1><p>입력을 바꿔 예측하고, 결과를 확인하세요.</p></div><div class="lab-tabs" role="tablist" aria-label="실습 종류">${[['options','01','옵션 병합'],['presence','02','생략과 null'],['state','03','실행 구간'],['rust','04','Rust 코드']].map(([id,n,label])=>`<button role="tab" id="tab-${id}" aria-controls="lab-panel" aria-selected="${id===activeLab}" data-lab="${id}"><small>${n}</small>${label}</button>`).join('')}</div><section id="lab-panel" role="tabpanel" aria-labelledby="tab-${activeLab}"></section>`;document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>{activeLab=b.dataset.lab;playground();$('#tab-'+activeLab).focus();});$('.lab-tabs').onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const ids=['options','presence','state','rust'];const i=ids.indexOf(activeLab);activeLab=ids[(i+(e.key==='ArrowRight'?1:3))%4];playground();$('#tab-'+activeLab).focus();};renderLab();}
function renderLab(){const panel=$('#lab-panel');const output='<div class="lab-output"><div class="code-bar"><span>RESULT</span><span>실행 결과</span></div><pre id="lab-result" role="status" aria-live="polite">입력을 바꾼 뒤 실행해 보세요.</pre></div>';
 if(activeLab==='options'){panel.innerHTML=`<div class="lab-intro"><h2>마지막 계층이 최상위 키를 덮어씁니다.</h2><p>Binding → Profile → Run 순서입니다. 중첩 객체는 깊게 합치지 않고 통째로 교체합니다.</p><a href="${readHref('ko/42-options.md')}">42장으로 돌아가기 ↗</a></div><div class="lab-columns"><div><div class="input-grid">${[['binding','Binding 기본값','{"reasoning_effort":"low","a":{"x":1,"y":2}}'],['profile','Profile 옵션','{"reasoning_effort":"medium"}'],['run','Run 옵션','{"reasoning_effort":"high","a":{"x":3}}']].map(([id,label,value])=>`<label for="${id}">${label}<textarea id="${id}" spellcheck="false">${value}</textarea></label>`).join('')}</div><button id="lab-run" class="button primary">병합 실행 ${icon('arrow')}</button></div>${output}</div>`;$('#lab-run').onclick=()=>runLab(()=>mergeOptions(...['binding','profile','run'].map(id=>objectInput($('#'+id).value))));}
 if(activeLab==='presence'){panel.innerHTML=`<div class="lab-intro"><h2>생략과 명시적인 null은 다릅니다.</h2><p>present가 false이면 필드를 생략합니다. 이때 value는 반드시 null이어야 합니다.</p><a href="${readHref('ko/43-provider-contracts.md')}">43장으로 돌아가기 ↗</a></div><div class="lab-columns"><div><label for="presence-input">Wire 입력<textarea id="presence-input" spellcheck="false">{"present": false, "value": null}</textarea></label><div class="preset-row"><button class="subtle" data-preset='{"present":false,"value":null}'>생략</button><button class="subtle" data-preset='{"present":true,"value":null}'>명시 null</button><button class="subtle" data-preset='{"present":false,"value":"memo"}'>잘못된 입력</button></div><button id="lab-run" class="button primary">인자 복원 ${icon('arrow')}</button></div>${output}</div>`;document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{$('#presence-input').value=b.dataset.preset;});$('#lab-run').onclick=()=>runLab(()=>decodePresence(JSON.parse($('#presence-input').value)));}
 if(activeLab==='state'){panel.innerHTML=`<div class="lab-intro"><h2>실행은 이어져도, 이전 결과는 남습니다.</h2><p>대기하거나 중단한 뒤 재개하면 새 segment를 시작합니다. 옛 handle의 결과는 바뀌지 않습니다.</p><a href="${readHref('ko/48-controls.md')}">48장으로 돌아가기 ↗</a></div><div class="state-board"><div class="state-now"><span class="eyebrow">CURRENT SEGMENT</span><strong id="segment-id"></strong><span id="run-state" class="pill accent"></span></div><div class="state-history"><p class="eyebrow">SAVED OUTCOMES</p><ol id="state-history"></ol></div></div><div class="state-actions">${[['wait','승인 대기'],['stop','중단'],['resume','재개'],['finish','완료'],['cancel','취소'],['reset','초기화']].map(([a,l])=>`<button class="button ${a==='resume'?'primary':'secondary'}" data-transition="${a}">${l}</button>`).join('')}</div><p id="state-message" role="status"></p>`;document.querySelectorAll('[data-transition]').forEach(b=>b.onclick=()=>{labState=transition(labState,b.dataset.transition);updateState();});updateState();}
 if(activeLab==='rust'){panel.innerHTML=`<div class="lab-intro"><h2>Rust를 직접 고치고 실행해 보세요.</h2><p>표준 라이브러리 예제입니다. 공식 Rust Playground를 새 탭으로 열어 실제 컴파일·실행합니다.</p><a href="${readHref('ko/01-rust.md')}">Rust 기초 강의 ↗</a></div><div class="preset-row">${Object.entries(rustExamples).map(([id,x])=>`<button class="subtle" data-rust="${id}">${x.label}</button>`).join('')}</div><label for="rust-code">Rust 2024 · 표준 라이브러리<textarea id="rust-code" class="rust-editor" spellcheck="false">${escape(rustExamples.ownership.code)}</textarea></label><div class="rust-actions"><button id="rust-open" class="button primary">Rust Playground에서 실행 ↗</button><button id="rust-download" class="button secondary">main.rs 내려받기</button></div><p class="lab-note">실행 버튼을 누르면 작성한 코드가 play.rust-lang.org로 전달됩니다. 비밀값을 넣지 마세요. Wickle crate·Tokio·SQLite 전체 실습은 교재의 로컬 Cargo 환경에서 실행합니다.</p>`;document.querySelectorAll('[data-rust]').forEach(b=>b.onclick=()=>{$('#rust-code').value=rustExamples[b.dataset.rust].code;});$('#rust-open').onclick=()=>{const code=$('#rust-code').value;if(new TextEncoder().encode(code).length>12000){toast('코드가 길어 URL로 열 수 없습니다. 파일로 내려받아 로컬에서 실행하세요.');return;}window.open(rustPlaygroundUrl(code),'_blank','noopener,noreferrer');};$('#rust-download').onclick=()=>{const u=URL.createObjectURL(new Blob([$('#rust-code').value],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='main.rs';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};}
 if(activeLab!=='rust')panel.insertAdjacentHTML('beforeend','<p class="lab-note">브라우저에서 실행하는 개념 실습입니다. 실제 Wickle 엔진·권한 검사·영속 저장을 실행하지 않습니다. JSON 실습은 JavaScript 수치 범위 안에서 사용하세요.</p>');}
function runLab(fn){try{$('#lab-result').textContent=JSON.stringify(fn(),null,2);$('#lab-result').classList.remove('error');}catch(e){$('#lab-result').textContent='입력 오류: '+e.message;$('#lab-result').classList.add('error');}}
function updateState(){$('#segment-id').textContent=String(labState.segment).padStart(2,'0');$('#run-state').textContent=labState.status;$('#state-message').textContent=labState.message;$('#state-history').innerHTML=labState.history.length?labState.history.map(x=>`<li><span>구간 ${x.segment}</span><strong>${x.status}</strong></li>`).join(''):'<li>아직 저장된 구간 결과가 없습니다.</li>';}
async function route(){const myToken=++token;toggleMenu(false);const hash=location.hash.slice(1)||'/';currentPath='';document.querySelectorAll('[data-path]').forEach(a=>a.removeAttribute('aria-current'));if(hash==='/playground'){playground();window.scrollTo(0,0);return;}if(hash.startsWith('/read/')){try{const [raw,query='']=hash.slice(6).split('?');const path=decodeURIComponent(raw);const section=new URLSearchParams(query).get('section');document.querySelectorAll('[data-path]').forEach(a=>{if(a.dataset.path===path){a.setAttribute('aria-current','page');a.closest('details').open=true;}});await read(path,section,myToken);}catch{notFound();}return;}if(hash==='/'||hash===''){home();window.scrollTo(0,0);}else notFound();}
(async()=>{try{catalog=await getJSON(base+'catalog.json');chapters=catalog.documents.filter(d=>d.kind==='chapter').sort((a,b)=>a.path.localeCompare(b.path,'en',{numeric:true}));shell();window.addEventListener('hashchange',route);await route();}catch(e){$('#app').innerHTML=`<div class="boot"><h1>Wickle 웹북</h1><p>${escape(e.message)}</p><p>네트워크 연결 또는 교재 파일 주소를 확인해 주세요.</p><button class="button primary" id="reload">다시 시도</button></div>`;$('#reload').onclick=()=>location.reload();}})();
